name: Setup Zui
description: Shared steps for setting up Zui in workflows
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20"

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version-file: .node-version

    # Python version is pinned to something <3.12 to work around:
    # https://github.com/brimdata/zui/issues/2882
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache NextJS Artifacts
      uses: jongwooo/next-cache@v1

    - name: Yarn Install
      run: yarn --inline-builds
      shell: bash

    - name: Yarn Build
      run: yarn run build
      shell: bash
