name: Setup App
description: Shared steps for setting up the app in workflows
runs:
  using: 'composite'
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        # Caching is disabled because it resulted in getting amd64 Zed binaries
        # on arm64 builds. See https://github.com/actions/setup-node/issues/1008.
        node-version-file: .node-version

    - name: Cache NextJS Artifacts
      uses: jongwooo/next-cache@v1

    - name: Yarn Install
      run: yarn --inline-builds
      shell: bash

    - name: Yarn Build
      run: yarn run build
      shell: bash
