name: Build Zui
description: Build Zui for the current platform
inputs:
  cmd:
    required: false
    default: yarn electron-builder
  gh_token:
    required: true

  # Windows Inputs
  csc_key_password:
    required: true
  csc_link:
    required: true

  # Mac Inputs
  apple_id:
    required: true
  apple_id_password:
    required: true
  cert_p12:
    required: true
  cert_passphrase:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install rpm
      if: runner.os == 'Linux'
      run: sudo apt-get install -y rpm
      shell: bash

    - name: Set developer ID certificate in keychain
      if: runner.os == 'macOS'
      run: |
        security create-keychain -p password build
        security default-keychain -s build
        security unlock-keychain -p password build
        f=$(mktemp)
        echo ${{ inputs.cert_p12 }} | base64 -d > $f
        security import $f -k build -A -T /usr/bin/codesign -T /usr/bin/security -f pkcs12  -P ${{ inputs.cert_passphrase }}
        rm $f
        security set-key-partition-list -S apple-tool:,apple: -k password build
        security find-identity -p codesigning -v
      shell: bash

    - name: Warm up build for Mac
      if: runner.os == 'macOS'
      # We've observed a problem with the new build system where the
      # notarization consistently fails because of an alleged lack of signing
      # of the file Corelight-CommunityID.darwin-x86_64.so. After much futile
      # debug, since these Zeek pieces are not expected to be part of the Brim
      # build for much longer, for now we're using the workaround of just
      # running the build step twice, as we've observed that it works
      # consistently on a retry.
      # On the retry we've observed the "hanging" symptom similar to what's
      # described at https://github.com/electron/electron-packager/issues/701.
      # As implied there, repeating the "security" commands gets past the
      # problem.
      run: |
        ${{ inputs.cmd }} || true
        security set-key-partition-list -S apple-tool:,apple: -k password build
        security find-identity -p codesigning -v
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        APPLE_ID: ${{ inputs.apple_id }}
        APPLE_ID_PASSWORD: ${{ inputs.apple_id_password }}
      shell: bash

    - name: Build & Publish
      run: ${{ inputs.cmd }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        CSC_KEY_PASSWORD: ${{ inputs.csc_key_password }}
        CSC_LINK: ${{ inputs.csc_link }}
        APPLE_ID: ${{ inputs.apple_id }}
        APPLE_ID_PASSWORD: ${{ inputs.apple_id_password }}

    - name: Check notorization with gatekeeper
      if: runner.os == 'macOS'
      run: |
        spctl --assess --type execute --verbose --ignore-cache --no-cache dist/installers/mac/*.app
      shell: bash
