name: Build Zui
description: Build Zui for the current platform
inputs:
  cmd:
    required: false
    default: yarn electron-builder
  gh_token:
    required: true

  # Windows Inputs
  csc_key_password:
    required: true
  csc_link:
    required: true

  # Mac Inputs
  apple_id:
    required: true
  apple_id_password:
    required: true
  apple_team_id:
    required: true
  cert_p12:
    required: true
  cert_passphrase:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install rpm
      if: runner.os == 'Linux'
      run: sudo apt-get install -y rpm
      shell: bash

    - name: Setup Xcode 13 # This lets us use the new notarytool cli
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "13.0"

    - name: Set developer ID certificate in keychain
      if: runner.os == 'macOS'
      run: |
        security create-keychain -p password build
        security default-keychain -s build
        security unlock-keychain -p password build
        f=$(mktemp)
        echo ${{ inputs.cert_p12 }} | base64 -d > $f
        security import $f -k build -A -T /usr/bin/codesign -T /usr/bin/security -f pkcs12  -P ${{ inputs.cert_passphrase }}
        rm $f
        security set-key-partition-list -S apple-tool:,apple: -k password build
        security find-identity -p codesigning -v
      shell: bash

    - name: Build & Publish
      run: ${{ inputs.cmd }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        WIN_CSC_KEY_PASSWORD: ${{ inputs.csc_key_password }}
        WIN_CSC_LINK: ${{ inputs.csc_link }}
        APPLE_ID: ${{ inputs.apple_id }}
        APPLE_ID_PASSWORD: ${{ inputs.apple_id_password }}
        APPLE_TEAM_ID: ${{ inputs.apple_team_id }}

    - name: Check notorization with gatekeeper
      if: runner.os == 'macOS'
      run: |
        spctl --assess --type execute --verbose --ignore-cache --no-cache dist/installers/mac/*.app
      shell: bash
