name: Brim CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version-file: .nvmrc
      - run: yarn --inline-builds
      - run: yarn lint
      - run: yarn test
      - name: Build and install package
        if: runner.os != 'Windows'
        run: |
          set -x
          yarn build
          case ${{ runner.os }} in
            Linux )
              yarn electron-builder --linux=deb
              sudo apt install -y --no-install-recommends ./dist/installers/*.deb
              ;;
            macOS )
              yarn electron-builder --mac=dir
              cp -r dist/installers/mac/Brim.app /Applications
              ;;
          esac
      - name: End to end tests
        id: playwright
        if: runner.os == 'Linux'
        uses: GabrielBB/xvfb-action@v1
        with:
          options: -screen 0 1280x1024x24
          run: yarn e2e
        env:
          DEBUG: pw:api
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            run
            !run/**/SS
