name: Zui CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04, windows-2019]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-zui
      - run: yarn lint
      - run: yarn test
      - name: Build and install package
        if: runner.os != 'Windows'
        run: |
          set -x
          case ${{ runner.os }} in
            Linux )
              yarn electron-builder --linux=deb --publish never
              sudo apt install -y --no-install-recommends ./installers/*.deb
              ;;
          esac
