name: Zui CI

on:
  pull_request:
  push:
    branches:
      - debug-zq-test
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-zui
      - run: |
          while true; do
            nx run zed-node:test
          done
