name: Zui CI

on:
  pull_request:
  push:
    branches:
      - debug-zq-test
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-zui
      - run: |
          npm add --global nx@latest
          NUM=1
          while true; do
            echo "Run number ${NUM}:"
            nx run zed-node:test --skip-nx-cache
            NUM=$(expr $NUM + 1)
          done
