name: Brim CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: setup node version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
    - run: npm install --no-audit
    - run: npm run format-check
    - run: npm run build
    - run: npm run lint
    - run: npm run flow
    - run: npm test -- --maxWorkers=2 --ci

  integration_test:
    runs-on: ubuntu-18.04
    container:
      image: brimsec/ci:0.0.1-zeek-mergecap
      options: --user root # circleci dockerfile that we derive from has USER circleci, which then can't write to mounted volumes
    strategy:
      matrix:
        node-version: [12.x]
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: setup node version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
    - run: npm install --no-audit
    - run: npm run build
    - name: Get ZQD
      run: |
        git clone --single-branch https://github.com/brimsec/zq
        cd zq
        git reset --hard da56b01d87a9745c90d09e960163ecba33eab55a
        make install
    - run: |
        npm run itest
