name: Brim CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 14.x ]
        os: [ windows-2019 ]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - name: setup node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Set NPM Cache Directory
        id: set-npm-cache-dir
        run: echo "::set-output name=npm_cache_dir::$(npm config get cache)"
      - name: Clear Extraneous Runner Cache
        # Clear on-runner cache before we create our own cache to prevent
        # slower build times. See https://github.com/brimdata/brim/pull/590
        # and https://github.com/brimdata/brim/issues/641
        run: rm -rf "${NPM_CACHE:?}"
        env:
          NPM_CACHE: ${{ steps.set-npm-cache-dir.outputs.npm_cache_dir }}
        shell: bash
      - name: Cache node modules
        uses: actions/cache@v2
        # Change the cache name any time you want to start with a cleared
        # cache.
        env:
          cache-name: cache-node-modules-ci-v5
        with:
          path: ${{ steps.set-npm-cache-dir.outputs.npm_cache_dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
      - run: npm install --no-audit
      - run: npm run format-check
      - run: npm run build
      - run: npm run lint
      - run: npm run tsc
      - run: npm test -- --maxWorkers=2 --ci
      - run: npm run test:api
      - run: npm run generate-responses -- --silent
      - name: Build Linux Packages
        if: runner.os == 'Linux'
        run: |
          set -x
          npx electron-builder --linux
      - name: Persist Linux packages
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: linux-release
          path: dist/installers/Brim-*

  integration_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 14.x ]
        os: [ windows-2019 ]
    needs: build
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: setup node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set NPM Cache Directory
        id: set-npm-cache-dir
        run: echo "::set-output name=npm_cache_dir::$(npm config get cache)"
      - name: Clear Extraneous Runner Cache
        run: rm -rf "${NPM_CACHE:?}"
        env:
          NPM_CACHE: ${{ steps.set-npm-cache-dir.outputs.npm_cache_dir }}
        shell: bash
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-ci-v5
        with:
          path: ${{ steps.set-npm-cache-dir.outputs.npm_cache_dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
      - run: npm install --no-audit
      - run: npm run build
      - run: npm run clean -- --keepDist
#      - name: Integration Tests (non-Linux)
#        if: runner.os != 'Linux'
#        run: npm run itest -- --ci --forceExit
#        env:
#          WORKSPACE: /var/tmp/brimdata
      - name: Install Choco and SSH server (Windows)
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install -y openssh -params '"/SSHServerFeature /KeyBasedAuthenticationFeature"'
        shell: powershell
      - name: Start SSH via Ngrok (Windows)
        run: |
          curl -sL https://gist.githubusercontent.com/mason-fish/cbaf2ebdf8437cb4401b9aaf03e443a7/raw/a5d0fba00ccda9c72975025341e770dbdc12830b/windows_ngrok.sh | bash
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          USER_PASS: ${{ secrets.NGROK_PASS }}
        shell: bash
      - name: Keep alive
        run: sleep 1h
        shell: bash
#      - uses: actions/upload-artifact@v2
#        if: failure()
#        with:
#          name: artifacts-${{ matrix.os }}-node-${{ matrix.node-version }}
#          path: /var/tmp/brimdata/itest
