name: Zui CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - name: Start SSH via ngrok
        run: ./start_ngrok_tunnel.sh
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          SSH_PUBLIC_KEY: ${{ secrets.NGROK_SSH_PUBLIC_KEY }}
        shell: bash
      - uses: ./.github/actions/setup-zui
      - run: yarn lint
      - run: yarn test
      - name: Build and install package
        if: runner.os != 'Windows'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          case ${{ runner.os }} in
            Linux )
              yarn nx package-zui zui --linux=deb --publish never
              sudo apt install -y --no-install-recommends ./dist/apps/zui/*.deb
              ;;
          esac
