name: Zui CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-12 is is Intel-based (x64), macos-14 is Apple Silicon (arm64)
        os: [macos-12, macos-14, ubuntu-20.04, windows-2019]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-zui
      - run: yarn lint
      - run: yarn test
      - name: Build and install package
        if: runner.os != 'Windows'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          case ${{ runner.os }} in
            Linux )
              yarn nx package-zui zui --publish never
              sudo apt install -y --no-install-recommends ./dist/apps/zui/*.deb
              ;;
          esac
      - name: Persist Linux RPM package
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: linux-release
          path: dist/apps/zui/*.rpm

  test-rpm-linux:
    runs-on: ubuntu-20.04
    needs: build
    container:
      image: rockylinux:9.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: dnf install -y xorg-x11-server-Xvfb git
      - run: git config --global core.autocrlf false
      - name: Download rpm package
        uses: actions/download-artifact@v4
        with:
          name: linux-release
          path: linux-release
      - name: Run tests on Rocky Linux (RPM installer)
        run: |
          dnf install -y ./linux-release/zui*.rpm
          xvfb-run -d -s "-screen 0 1280x1024x24" yarn test
