name: Brim CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version-file: .nvmrc
      - run: npm install --no-audit
      - run: npm run build
      - run: npm run lint
      - run: npm run tsc
      - run: npm test -- --maxWorkers=2 --ci
      - run: npm run test:api
      - run: npm run generate-responses -- --silent
      - name: Build and install package
        if: runner.os == 'Linux'
        run: |
          set -x
          npx electron-builder --linux=deb
          sudo apt install -y --no-install-recommends ./dist/installers/*.deb
      - name: Playwright tests
        id: playwright
        if: runner.os != 'Windows'
        uses: GabrielBB/xvfb-action@v1
        with:
          options: -screen 0 1280x1024x24
          run: npm run test:playwright -- --ci --forceExit
        env:
          DEBUG: pw:api
      - uses: actions/upload-artifact@v2
        if: failure() && steps.playwright.outcome == 'failure'
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            run/playwright-itest
            !run/**/SS
