name: Run e2e tests

on:
  workflow_dispatch:
    inputs:
      run-target:
        description: Command line for running e2e tests
        default: 'yarn e2e:ci'
        required: true
      platforms:
        description: OS platforms to test on (list of strings in JSON format)"
        default: '["ubuntu-20.04"]'
        required: true
jobs:
  run-e2e-tests:
    name: Run e2e tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.platforms) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-zui
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - name: End to end tests
        id: playwright
        uses: GabrielBB/xvfb-action@v1
        with:
          options: -screen 0 1280x1024x24
          run: ${{ inputs.run-target }}
      - uses: actions/upload-artifact@v2
        if: failure() && steps.playwright.outcome == 'failure'
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            packages/zui-player/run/playwright-itest
            packages/zui-player/test-results
            /var/log/sys*log*
            /var/log/kern.log*
