name: Release

on:
  push:

jobs:
  release:
    strategy:
      matrix:
        platform: [Windows, Mac, Linux]
        include:
          - platform: Windows
            runner: windows-2019

          - platform: Mac
            runner: macos-10.15

          - platform: Linux
            runner: ubuntu-18.04

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Zui
        uses: actions/checkout@v3

      - name: Setup Zui
        uses: ./.github/actions/setup-zui

      - name: Build Zui
        uses: ./.github/actions/build-zui
        with:
          cmd: yarn electron-builder
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          # Windows
          csc_key_password: ${{ secrets.WINDOWS_SIGNING_PASSPHRASE }}
          csc_link: ${{ secrets.WINDOWS_SIGNING_PFX_BASE64 }}
          # Mac
          apple_id: ${{ secrets.APPLEID_USER }}
          apple_id_password: ${{ secrets.APPLEID_PASSWORD }}
          cert_p12: ${{ secrets.APPLE_DEVELOPER_ID_CERT_P12_BASE64 }}
          cert_passphrase: ${{ secrets.APPLE_DEVELOPER_ID_CERT_PASSPHRASE }}
