name: Test Uploading to A Insiders Release

on:
  push:
    branches:
      - 'release-insiders/**'

jobs:
  upload:
    name: Upload the Build Shaw
    runs-on: ubuntu-20.04
    steps:
      - name: Create the build_sha file
        run: echo ${{ github.sha }} > build_sha.txt

      - name: Get Latest Release Tag
        id: latest
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: brimdata
          repo: zui-insiders

      - name: Upload build_sha File to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: build_sha.txt
          tag: ${{ steps.latest.outputs.release }}
          repo_name: brimdata/zui-insiders
          repo_token: ${{ secrets.PAT_TOKEN }}
          overwrite: true
